spring:
  application:
    name: "mavg-challenge"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres


logging:
  level:
    io.mavg.challenge: debug

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

springdoc:
  show-actuator: true
  show-login-endpoint: true

jwt:
  secret: 4An6aT4nreYL4nN56YePq6pT5SF8CvXk